apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/koustavnaha11/3tier-java-mysql-helm-charts-repo.git'
    targetRevision: HEAD
    path: 3-tier-java-mysql-helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
