apiVersion: v1
kind: Service
metadata:
  name: my-springboot-service
spec:
  type: NodePort
  selector:
    app: my-springboot-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.springboot.nodePort }}
